---
parent: central
serviceName: plivo-dotnet
language: dotnet-sdk
build:
  command: |
      dotnet build --configuration Release
      cd src/Plivo && ./pack.sh
postDeployJobs:
  prod:
    - name: plivo/messaging-qa/dotnetSDKSmoke
      disabled: false
